### ISSUE TITLE
Administration Hub

### ISSUE THREAD

**Issue by abuneri** [sfuesss/website#4]
This will create an easy way for site admins to edit, update, and add content.

**Comment by abuneri** [comment]
creating an admin zone (requires login) where the user will be able to update key information that is changing all the time or on a per semester basis (e.g. office hours, sponsors, member roles, merchandise ,etc)

**Comment by abuneri** [comment]
Improving the folder structure for our files (pictures)

**Comment by SFU-ESSS** [comment]
> This will create an easy way for site admins to edit, update, and add content.

Hi are you currently the owner of the ESSS github organization. If so can you transfer ownership (or admin privileges) to this account. If not, then are you aware of who setup the organization? Thanks in advance and hope to hear from you.

Sincerely,
SS

**Comment by shaynekellyii** [comment]
> > This will create an easy way for site admins to edit, update, and add content.
> 
> Hi are you currently the owner of the ESSS github organization. If so can you transfer ownership (or admin privileges) to this account. If not, then are you aware of who setup the organization? Thanks in advance and hope to hear from you.
> 
> Sincerely, SS

Looks like this repo was started when I was still around in the ESSS and I have no idea who created it unfortunately. Alvin David (another one of the previous presidents of the ESSS) might know who had admin access to it?

**Comment by SFU-ESSS** [comment]
> > > This will create an easy way for site admins to edit, update, and add content.
> > 
> > 
> > Hi are you currently the owner of the ESSS github organization. If so can you transfer ownership (or admin privileges) to this account. If not, then are you aware of who setup the organization? Thanks in advance and hope to hear from you.
> > Sincerely, SS
> 
> Looks like this repo was started when I was still around in the ESSS and I have no idea who created it unfortunately. Alvin David (another one of the previous presidents of the ESSS) might know who had admin access to it?

Hi Shayne, Thank you for reaching out! I've asked alvin and hope to hear from him soon! I was wondering if you have collaborator access and could add this account to the website repo so that it can be updated. Additionally, are you by any chance in contact with abuneri/sedruk by any chance?
